import { useSignUp } from "@clerk/expo";
import { Link, useRouter, type Href } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, View } from "react-native";
import AuthField from "@/components/AuthField";
import { getClerkErrorMessage, type AuthErrors } from "@/lib/auth";

export default function ContinueSignUp() {
  const router = useRouter(); const { signUp, fetchStatus } = useSignUp();
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [accepted, setAccepted] = useState(false); const [errors, setErrors] = useState<AuthErrors>({}); const [submitting, setSubmitting] = useState(false); const loading = submitting || fetchStatus === "fetching";
  const missing = signUp.missingFields ?? [];
  const needsFirstName = missing.includes("first_name"); const needsLastName = missing.includes("last_name"); const needsLegal = missing.includes("legal_accepted");
  const submit = async () => { const nextErrors: AuthErrors = {}; if (needsFirstName && !firstName.trim()) nextErrors.firstName = "Enter your first name."; if (needsLastName && !lastName.trim()) nextErrors.lastName = "Enter your last name."; if (needsLegal && !accepted) nextErrors.legal = "Accept the terms to continue."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setErrors({}); setSubmitting(true); try { const result = await signUp.update({ ...(needsFirstName ? { firstName: firstName.trim() } : {}), ...(needsLastName ? { lastName: lastName.trim() } : {}), ...(needsLegal ? { legalAccepted: true } : {}) }); if (result.error) { setErrors({ form: getClerkErrorMessage(result.error, "We couldn't save your account details.") }); return; } if (signUp.status === "complete") { const finalized = await signUp.finalize(); if (finalized.error) setErrors({ form: getClerkErrorMessage(finalized.error, "We couldn't finish creating your account.") }); else router.replace("/(tabs)"); } else setErrors({ form: `Please complete: ${(signUp.missingFields ?? []).join(", ")}.` }); } catch (error) { setErrors({ form: getClerkErrorMessage(error, "We couldn't save your account details.") }); } finally { setSubmitting(false); } };
  if (signUp.status !== "missing_requirements") return null;
  return <KeyboardAvoidingView className="auth-safe-area" behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView className="auth-scroll" contentContainerClassName="auth-content" keyboardShouldPersistTaps="handled"><View className="auth-brand-block"><View className="auth-logo-wrap"><View className="auth-logo-mark"><Text className="auth-logo-mark-text">R</Text></View><View><Text className="auth-wordmark">Recurrly</Text><Text className="auth-wordmark-sub">Smart billing</Text></View></View><Text className="auth-title">Complete your account</Text><Text className="auth-subtitle">Add a few details so we can finish setting up your Recurrly account.</Text></View><View className="auth-card"><View className="auth-form">{needsFirstName ? <AuthField label="First name" value={firstName} onChangeText={setFirstName} autoCapitalize="words" placeholder="Enter your first name" error={errors.firstName} /> : null}{needsLastName ? <AuthField label="Last name" value={lastName} onChangeText={setLastName} autoCapitalize="words" placeholder="Enter your last name" error={errors.lastName} /> : null}{needsLegal ? <Pressable onPress={() => setAccepted((value) => !value)} className="flex-row items-center gap-3"><View className={`size-6 rounded-md border border-accent ${accepted ? "bg-accent" : "bg-background"}`} /> <Text className="auth-helper flex-1">I agree to the Recurrly terms and privacy policy.</Text></Pressable> : null}{errors.legal ? <Text className="auth-error">{errors.legal}</Text> : null}{errors.form ? <Text className="auth-error">{errors.form}</Text> : null}<Pressable disabled={loading} onPress={submit} className={`auth-button ${loading ? "auth-button-disabled" : ""}`}>{loading ? <ActivityIndicator color="#081126" /> : <Text className="auth-button-text">Finish setup</Text>}</Pressable><View nativeID="clerk-captcha" /></View><View className="auth-link-row"><Text className="auth-link-copy">Need to start over?</Text><Link href={"/(auth)/sign-in" as Href} className="auth-link">Back to sign in</Link></View></View></ScrollView></KeyboardAvoidingView>;
}
