import { useSignIn } from "@clerk/expo";
import { Link, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, View } from "react-native";
import AuthField from "@/components/AuthField";
import { getClerkErrorMessage, normalizeEmail, validateEmail, validatePassword, type AuthErrors } from "@/lib/auth";

export default function ForgotPassword() {
  const router = useRouter(); const { signIn, fetchStatus } = useSignIn();
  const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [step, setStep] = useState<"email" | "code" | "password">("email"); const [errors, setErrors] = useState<AuthErrors>({}); const [submitting, setSubmitting] = useState(false); const loading = submitting || fetchStatus === "fetching";
  const sendCode = async () => { const emailError = validateEmail(email); if (emailError) { setErrors({ email: emailError }); return; } setErrors({}); setSubmitting(true); try { const created = await signIn.create({ identifier: normalizeEmail(email) }); if (created.error) { setErrors({ form: getClerkErrorMessage(created.error, "We couldn't find an account with that email.") }); return; } const sent = await signIn.resetPasswordEmailCode.sendCode(); if (sent.error) { setErrors({ form: getClerkErrorMessage(sent.error, "We couldn't send a reset code.") }); return; } setStep("code"); } catch (error) { setErrors({ form: getClerkErrorMessage(error, "We couldn't start password recovery.") }); } finally { setSubmitting(false); } };
  const verifyCode = async () => { if (!/^\d{4,8}$/.test(code.trim())) { setErrors({ code: "Enter the reset code from your email." }); return; } setErrors({}); setSubmitting(true); try { const result = await signIn.resetPasswordEmailCode.verifyCode({ code: code.trim() }); if (result.error) setErrors({ code: getClerkErrorMessage(result.error, "That code is invalid or expired.") }); else setStep("password"); } catch (error) { setErrors({ code: getClerkErrorMessage(error, "We couldn't verify that code.") }); } finally { setSubmitting(false); } };
  const updatePassword = async () => { const passwordError = validatePassword(password); const nextErrors: AuthErrors = {}; if (passwordError) nextErrors.password = passwordError; if (password !== confirmPassword) nextErrors.confirmPassword = "Passwords do not match."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setErrors({}); setSubmitting(true); try { const result = await signIn.resetPasswordEmailCode.submitPassword({ password, signOutOfOtherSessions: true }); if (result.error) { setErrors({ form: getClerkErrorMessage(result.error, "We couldn't update your password.") }); return; } const finalized = await signIn.finalize(); if (finalized.error) setErrors({ form: getClerkErrorMessage(finalized.error, "We couldn't finish signing you in.") }); else router.replace("/(tabs)"); } catch (error) { setErrors({ form: getClerkErrorMessage(error, "We couldn't update your password.") }); } finally { setSubmitting(false); } };
  return <KeyboardAvoidingView className="auth-safe-area" behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView className="auth-scroll" contentContainerClassName="auth-content" keyboardShouldPersistTaps="handled"><View className="auth-brand-block"><View className="auth-logo-wrap"><View className="auth-logo-mark"><Text className="auth-logo-mark-text">R</Text></View><View><Text className="auth-wordmark">Recurrly</Text><Text className="auth-wordmark-sub">Smart billing</Text></View></View><Text className="auth-title">Reset your password</Text><Text className="auth-subtitle">We’ll help you get back to your subscriptions.</Text></View><View className="auth-card"><View className="auth-form">{step === "email" && <><AuthField label="Email" value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" placeholder="Enter your email" error={errors.email} /><Text className="auth-helper">We’ll email you a secure reset code.</Text><Pressable disabled={loading} onPress={sendCode} className={`auth-button ${loading ? "auth-button-disabled" : ""}`}>{loading ? <ActivityIndicator color="#081126" /> : <Text className="auth-button-text">Send reset code</Text>}</Pressable></>}{step === "code" && <><Text className="text-xl font-sans-bold text-primary">Check your inbox</Text><Text className="auth-helper">Enter the code sent to {normalizeEmail(email)}.</Text><AuthField label="Reset code" value={code} onChangeText={setCode} keyboardType="number-pad" textContentType="oneTimeCode" placeholder="Enter your code" error={errors.code} /><Pressable disabled={loading} onPress={verifyCode} className={`auth-button ${loading ? "auth-button-disabled" : ""}`}>{loading ? <ActivityIndicator color="#081126" /> : <Text className="auth-button-text">Verify code</Text>}</Pressable></>}{step === "password" && <><AuthField label="New password" value={password} onChangeText={setPassword} secure secureTextEntry placeholder="At least 8 characters" error={errors.password} /><AuthField label="Confirm password" value={confirmPassword} onChangeText={setConfirmPassword} secure secureTextEntry placeholder="Repeat your password" error={errors.confirmPassword} /><Pressable disabled={loading} onPress={updatePassword} className={`auth-button ${loading ? "auth-button-disabled" : ""}`}>{loading ? <ActivityIndicator color="#081126" /> : <Text className="auth-button-text">Update password</Text>}</Pressable></>}{errors.form ? <Text className="auth-error">{errors.form}</Text> : null}</View><View className="auth-link-row"><Text className="auth-link-copy">Remembered your password?</Text><Link href="/(auth)/sign-in" className="auth-link">Sign in</Link></View></View></ScrollView></KeyboardAvoidingView>;
}
