import { useSignUp } from "@clerk/expo";
import { Link, useRouter, type Href } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, View } from "react-native";
import AuthField from "@/components/AuthField";
import { getClerkErrorMessage, normalizeEmail, validateEmail, validatePassword, type AuthErrors } from "@/lib/auth";
import { posthog } from "@/lib/posthog";

export default function SignUp() {
  const router = useRouter(); const { signUp, fetchStatus } = useSignUp();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [code, setCode] = useState(""); const [verifying, setVerifying] = useState(false); const [showPassword, setShowPassword] = useState(false); const [errors, setErrors] = useState<AuthErrors>({}); const [submitting, setSubmitting] = useState(false);
  const createAccount = async () => { const nextErrors: AuthErrors = {}; const emailError = validateEmail(email); const passwordError = validatePassword(password); if (emailError) nextErrors.email = emailError; if (passwordError) nextErrors.password = passwordError; if (password !== confirmPassword) nextErrors.confirmPassword = "Passwords do not match."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setErrors({}); setSubmitting(true); try { const result = await signUp.password({ emailAddress: normalizeEmail(email), password }); if (result.error) { setErrors({ form: getClerkErrorMessage(result.error, "We couldn't create your account.") }); return; } const codeResult = await signUp.verifications.sendEmailCode(); if (codeResult.error) { setErrors({ form: getClerkErrorMessage(codeResult.error, "We couldn't send your verification code.") }); return; } setVerifying(true); } catch (error) { posthog?.captureException(error, { flow: "sign_up", step: "create_account" }); setErrors({ form: getClerkErrorMessage(error, "We couldn't create your account. Please try again.") }); } finally { setSubmitting(false); } };
  const verify = async () => { if (!/^\d{4,8}$/.test(code.trim())) { setErrors({ code: "Enter the verification code from your email." }); return; } setErrors({}); setSubmitting(true); try { const result = await signUp.verifications.verifyEmailCode({ code: code.trim() }); if (result.error) { setErrors({ code: getClerkErrorMessage(result.error, "That code is invalid or expired.") }); return; } if (signUp.status === "complete") { const finalized = await signUp.finalize(); if (finalized.error) setErrors({ form: getClerkErrorMessage(finalized.error, "We couldn't finish creating your account.") }); else { posthog?.capture("account_created", { signup_method: "email" }); router.replace("/(tabs)"); } } else if (signUp.status === "missing_requirements") { router.replace("/(auth)/continue" as Href); } else { setErrors({ form: "We need a little more information to finish setting up your account." }); } } catch (error) { posthog?.captureException(error, { flow: "sign_up", step: "verify_email" }); setErrors({ form: getClerkErrorMessage(error, "We couldn't verify your email. Please try again.") }); } finally { setSubmitting(false); } };
  const resend = async () => { setErrors({}); setSubmitting(true); try { const result = await signUp.verifications.sendEmailCode(); if (result.error) setErrors({ form: getClerkErrorMessage(result.error, "We couldn't resend the code.") }); } catch (error) { posthog?.captureException(error, { flow: "sign_up", step: "resend_code" }); setErrors({ form: getClerkErrorMessage(error, "We couldn't resend the code.") }); } finally { setSubmitting(false); } };
  const loading = submitting || fetchStatus === "fetching";
  return <KeyboardAvoidingView className="auth-safe-area" behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView className="auth-scroll" contentContainerClassName="auth-content" keyboardShouldPersistTaps="handled"><View className="auth-brand-block"><View className="auth-logo-wrap"><View className="auth-logo-mark"><Text className="auth-logo-mark-text">R</Text></View><View><Text className="auth-wordmark">Recurrly</Text><Text className="auth-wordmark-sub">Smart billing</Text></View></View><Text className="auth-title">Create your account</Text><Text className="auth-subtitle">Stay ahead of every renewal with one clear view.</Text></View><View className="auth-card">{!verifying ? <View className="auth-form"><AuthField label="Email" value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" placeholder="Enter your email" error={errors.email} /><AuthField label="Password" value={password} onChangeText={setPassword} secure secureTextEntry={!showPassword} onToggleSecure={() => setShowPassword((value) => !value)} textContentType="newPassword" placeholder="At least 8 characters" error={errors.password} /><AuthField label="Confirm password" value={confirmPassword} onChangeText={setConfirmPassword} secure secureTextEntry={!showPassword} onToggleSecure={() => setShowPassword((value) => !value)} textContentType="newPassword" placeholder="Repeat your password" error={errors.confirmPassword} />{errors.form ? <Text className="auth-error">{errors.form}</Text> : null}<Pressable disabled={loading} onPress={createAccount} className={`auth-button ${loading ? "auth-button-disabled" : ""}`}>{loading ? <ActivityIndicator color="#081126" /> : <Text className="auth-button-text">Create account</Text>}</Pressable><View nativeID="clerk-captcha" /></View> : <View className="auth-form"><Text className="text-xl font-sans-bold text-primary">Check your inbox</Text><Text className="auth-helper">We sent a verification code to {normalizeEmail(email)}.</Text><AuthField label="Verification code" value={code} onChangeText={setCode} keyboardType="number-pad" textContentType="oneTimeCode" placeholder="Enter your code" error={errors.code} />{errors.form ? <Text className="auth-error">{errors.form}</Text> : null}<Pressable disabled={loading} onPress={verify} className={`auth-button ${loading ? "auth-button-disabled" : ""}`}>{loading ? <ActivityIndicator color="#081126" /> : <Text className="auth-button-text">Verify email</Text>}</Pressable><Pressable disabled={loading} onPress={resend} className="auth-secondary-button"><Text className="auth-secondary-button-text">Resend code</Text></Pressable></View>}<View className="auth-link-row"><Text className="auth-link-copy">Already have an account?</Text><Link href="/(auth)/sign-in" className="auth-link">Sign in</Link></View></View></ScrollView></KeyboardAvoidingView>;
}
